# Generated by Django 4.0.5 on 2022-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.IntegerField()),
                ('languageFrom', models.CharField(max_length=20)),
                ('languageTo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FutureCourse',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('languageFrom', models.CharField(max_length=20)),
                ('languageTo', models.CharField(max_length=20)),
            ],
        ),
    ]
